spring.datasource.url=jdbc:mysql://localhost:3306/rideshare
spring.datasource.username=root
spring.datasource.password=tarun2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080