spring.application.name=chemical-safety-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/chemical_safety_db
spring.datasource.username=root
spring.datasource.password=tarun2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

server.port=8080